project 'ios-scopes/ios-scopes.xcodeproj'

source 'https://github.com/flybits/Spec-Xcode-11.3.1.git'

target 'ios-scopes' do
  use_frameworks!
  pod 'FlybitsKernelSDK', '3.3.0'
  pod 'FlybitsPushSDK', '3.3.0'
  pod 'FlybitsContextLocationPluginSDK', '3.3.0'
  pod 'FlybitsContextSDK', '3.3.0'
  pod 'FlybitsConciergeSDK', '3.3.0'
end

